USE [dbDOC]
GO

/****** Object:  Table [dbo].[TT_DOC_UKETORI_IF]    Script Date: 2015/12/25 10:43:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TT_DOC_UKETORI_IF](
	[ID] [int] IDENTITY(0,1) NOT NULL,
	[RACK_FILE_NO] [varchar](5) NULL,
	[KEI_CAR_FLG] [char](1) NULL,
	[TOROKU_NO] [varchar](24) NULL,
	[HYOBAN_TYPE] [char](1) NULL,
	[CHASSIS_NO] [varchar](25) NULL,
	[GENDOKI_KATASHIKI] [varchar](12) NULL,
	[REPORT_TYPE] [char](1) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER_CD] [varchar](10) NULL,
	[CREATE_PG_CD] [varchar](10) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER_CD] [varchar](10) NULL,
	[UPDATE_PG_CD] [varchar](10) NULL,
	[DELETE_DATE] [datetime] NULL,
	[DELETE_FLG] [char](1) NULL,
 CONSTRAINT [PK_TT_DOC_UKETORI_IF] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [dbDOC_DATA]
) ON [dbDOC_DATA]

GO

SET ANSI_PADDING OFF
GO

