USE [dbDOC]
GO

/****** Object:  Table [dbo].[TM_DOC_HAITA_CONTROL]    Script Date: 2015/12/25 10:40:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TM_DOC_HAITA_CONTROL](
	[DOC_CONTROL_NO] [varchar](13) NOT NULL,
	[DOC_FUZOKUHIN_NAME] [char](3) NULL,
	[DOC_FUZOKUHIN_DISP_NAME] [varchar](10) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER_CD] [varchar](10) NULL,
	[CREATE_PG_CD] [varchar](10) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER_CD] [varchar](10) NULL,
	[UPDATE_PG_CD] [varchar](10) NULL,
	[DELETE_DATE] [datetime] NULL,
	[DELETE_FLG] [char](1) NULL,
 CONSTRAINT [PK_TM_DOC_HAITA_CONTROL] PRIMARY KEY CLUSTERED 
(
	[DOC_CONTROL_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [dbDOC_DATA]
) ON [dbDOC_DATA]

GO

SET ANSI_PADDING OFF
GO

