USE [dbDOC]
GO

/****** Object:  Table [dbo].[TT_DOC_JISHAMEI_MASSHO_IF]    Script Date: 2015/12/25 10:43:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TT_DOC_JISHAMEI_MASSHO_IF](
	[DOC_CONTROL_NO] [varchar](13) NOT NULL,
	[IRAI_DATE] [datetime] NULL,
	[SHOP_CD] [char](6) NULL,
	[GENSHA_LOCATION] [varchar](25) NULL,
	[CAR_NAME] [varchar](100) NULL,
	[CHASSIS_NO] [varchar](25) NULL,
	[JISHAME_MASSHO_TYPE] [char](3) NULL,
	[NOTE] [varchar](1000) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER_CD] [varchar](10) NULL,
	[CREATE_PG_CD] [varchar](10) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER_CD] [varchar](10) NULL,
	[UPDATE_PG_CD] [varchar](10) NULL,
	[DELETE_DATE] [datetime] NULL,
	[DELETE_FLG] [char](1) NULL,
 CONSTRAINT [PK_TT_DOC_JISHAMEI_MASSHO_IF] PRIMARY KEY CLUSTERED 
(
	[DOC_CONTROL_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [dbDOC_DATA]
) ON [dbDOC_DATA]

GO

SET ANSI_PADDING OFF
GO

