USE [dbDOC]
GO

/****** Object:  Table [dbo].[TM_CONST]    Script Date: 2015/12/25 10:39:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TM_CONST](
	[TYPE] [varchar](30) NOT NULL,
	[TYPE_VALUE] [varchar](30) NOT NULL,
	[VALUE] [varchar](1000) NULL,
	[NOTE] [varchar](1000) NULL,
	[DISP_ORDER] [int] NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER_CD] [varchar](10) NULL,
	[CREATE_PG_CD] [varchar](10) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER_CD] [varchar](10) NULL,
	[UPDATE_PG_CD] [varchar](10) NULL,
	[DELETE_DATE] [datetime] NULL,
	[DELETE_FLG] [char](1) NULL,
 CONSTRAINT [PK_TM_CONST] PRIMARY KEY CLUSTERED 
(
	[TYPE] ASC,
	[TYPE_VALUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [dbDOC_DATA]
) ON [dbDOC_DATA]

GO

SET ANSI_PADDING OFF
GO

