USE [dbDOC]
GO

/****** Object:  Table [dbo].[TT_DOC_UKETORI_DETAIL]    Script Date: 2015/12/25 10:43:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TT_DOC_UKETORI_DETAIL](
	[DOC_CONTROL_NO] [varchar](13) NOT NULL,
	[DOC_FUZOKUHIN_CD] [char](3) NOT NULL,
	[DOC_COUNT] [int] NULL,
	[DOC_HAKKO_DATE] [datetime] NULL,
	[DOC_UKE_DATE] [datetime] NULL,
	[NOTE] [varchar](200) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER_CD] [varchar](10) NULL,
	[CREATE_PG_CD] [varchar](10) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER_CD] [varchar](10) NULL,
	[UPDATE_PG_CD] [varchar](10) NULL,
	[DELETE_DATE] [datetime] NULL,
	[DELETE_FLG] [char](1) NULL,
 CONSTRAINT [PK_TT_DOC_UKETORI_DETAIL] PRIMARY KEY CLUSTERED 
(
	[DOC_CONTROL_NO] ASC,
	[DOC_FUZOKUHIN_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [dbDOC_DATA]
) ON [dbDOC_DATA]

GO

SET ANSI_PADDING OFF
GO

