USE [dbDOC]
GO

/****** Object:  Table [dbo].[TM_DOC_FUZOKUHIN]    Script Date: 2015/12/25 10:40:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TM_DOC_FUZOKUHIN](
	[DOC_FUZOKUHIN_CD] [char](3) NOT NULL,
	[DOC_FUZOKUHIN_NAME] [varchar](50) NULL,
	[DOC_FUZOKUHIN_DISP_NAME] [varchar](25) NULL,
	[DOC_FUZOKUHIN_TYPE_CD] [char](3) NULL,
	[UKETORIJI_DEFALT_CHECK_TYPE] [char](4) NULL,
	[BIKO_NYURYOKU_KAHI_FLG] [char](1) NULL,
	[DISP_ORDER] [int] NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER_CD] [varchar](10) NULL,
	[CREATE_PG_CD] [varchar](10) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER_CD] [varchar](10) NULL,
	[UPDATE_PG_CD] [varchar](10) NULL,
	[DELETE_DATE] [datetime] NULL,
	[DELETE_FLG] [char](1) NULL,
 CONSTRAINT [PK_TM_DOC_FUZOKUHIN] PRIMARY KEY CLUSTERED 
(
	[DOC_FUZOKUHIN_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [dbDOC_DATA]
) ON [dbDOC_DATA]

GO

SET ANSI_PADDING OFF
GO

