USE [dbDOC]
GO

/****** Object:  Table [dbo].[TM_TANTOSHA]    Script Date: 2015/12/25 10:41:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TM_TANTOSHA](
	[TANTOSHA_CD] [char](8) NOT NULL,
	[TANTOSHA_NAME] [varchar](40) NOT NULL,
	[PASSWORD] [varchar](20) NULL,
	[EXIST_FLG] [char](1) NULL,
	[RACK_SEACH_KANO_FLG] [char](1) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER_CD] [varchar](10) NULL,
	[CREATE_PG_CD] [varchar](10) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER_CD] [varchar](10) NULL,
	[UPDATE_PG_CD] [varchar](10) NULL,
	[DELETE_DATE] [datetime] NULL,
	[DELETE_FLG] [char](1) NULL,
 CONSTRAINT [PK_TM_TANTOSHA] PRIMARY KEY CLUSTERED 
(
	[TANTOSHA_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [dbDOC_DATA]
) ON [dbDOC_DATA]

GO

SET ANSI_PADDING OFF
GO

