//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gulliver.DoCol.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DC1010 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DC1010() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gulliver.DoCol.Constants.Resources.DC1010", typeof(DC1010).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログイン.
        /// </summary>
        public static string ButtonTextLogin {
            get {
                return ResourceManager.GetString("ButtonTextLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 認証モード.
        /// </summary>
        public static string LabelMode {
            get {
                return ResourceManager.GetString("LabelMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 店舗番号.
        /// </summary>
        public static string LabelShopID {
            get {
                return ResourceManager.GetString("LabelShopID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 社員番号.
        /// </summary>
        public static string LabelUserID {
            get {
                return ResourceManager.GetString("LabelUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APS店舗番号.
        /// </summary>
        public static string lblAPSStoreNo {
            get {
                return ResourceManager.GetString("lblAPSStoreNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHR社員番号.
        /// </summary>
        public static string lblGHRStaffNo {
            get {
                return ResourceManager.GetString("lblGHRStaffNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード_社員.
        /// </summary>
        public static string lblPassword_Staff {
            get {
                return ResourceManager.GetString("lblPassword_Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード_店舗.
        /// </summary>
        public static string lblPassword_Store {
            get {
                return ResourceManager.GetString("lblPassword_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログイン画面.
        /// </summary>
        public static string lblTitlePage {
            get {
                return ResourceManager.GetString("lblTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英数	パスワード_店舗.
        /// </summary>
        public static string passwordAlphanumericRequired {
            get {
                return ResourceManager.GetString("passwordAlphanumericRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード.
        /// </summary>
        public static string plhPassword {
            get {
                return ResourceManager.GetString("plhPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHR社員番号.
        /// </summary>
        public static string plhShainNo {
            get {
                return ResourceManager.GetString("plhShainNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APS店舗番号.
        /// </summary>
        public static string plhTempoNo {
            get {
                return ResourceManager.GetString("plhTempoNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英数	パスワード_社員.
        /// </summary>
        public static string pswAlphanumericRequired {
            get {
                return ResourceManager.GetString("pswAlphanumericRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 店舗用.
        /// </summary>
        public static string RadioMode1 {
            get {
                return ResourceManager.GetString("RadioMode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本部用.
        /// </summary>
        public static string RadioMode2 {
            get {
                return ResourceManager.GetString("RadioMode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英数	GHR社員番号.
        /// </summary>
        public static string shainNoAlphanumericRequired {
            get {
                return ResourceManager.GetString("shainNoAlphanumericRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英数	APS店舗番号.
        /// </summary>
        public static string tempoCdAlphanumericRequired {
            get {
                return ResourceManager.GetString("tempoCdAlphanumericRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 店舗情報：（APSのID、パスワードを入力してください。）.
        /// </summary>
        public static string TitleBar1 {
            get {
                return ResourceManager.GetString("TitleBar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 社員情報：（GHRの社員番号、パスワードを入力してください。）.
        /// </summary>
        public static string TitleBar2 {
            get {
                return ResourceManager.GetString("TitleBar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログイン.
        /// </summary>
        public static string TitleTop {
            get {
                return ResourceManager.GetString("TitleTop", resourceCulture);
            }
        }
    }
}
