//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gulliver.DoCol.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DCW002 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DCW002() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gulliver.DoCol.Constants.Resources.DCW002", typeof(DCW002).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取込み.
        /// </summary>
        public static string btnImport {
            get {
                return ResourceManager.GetString("btnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 棚卸し.
        /// </summary>
        public static string btnInventory {
            get {
                return ResourceManager.GetString("btnInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本日発送予定の&lt;br/&gt;書類を検索する(AA).
        /// </summary>
        public static string btnSearchAA {
            get {
                return ResourceManager.GetString("btnSearchAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 詳細条件で&lt;br/&gt;書類を検索する.
        /// </summary>
        public static string btnSearchDetail {
            get {
                return ResourceManager.GetString("btnSearchDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本日発送予定の&lt;br/&gt;書類を検索する(普通車).
        /// </summary>
        public static string btnSearchLightVehicles {
            get {
                return ResourceManager.GetString("btnSearchLightVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本日発送予定の&lt;br/&gt;書類を検索する(軽).
        /// </summary>
        public static string btnSearchLory {
            get {
                return ResourceManager.GetString("btnSearchLory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択.
        /// </summary>
        public static string btnSelectFile {
            get {
                return ResourceManager.GetString("btnSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 書類管理システム.
        /// </summary>
        public static string labelHeaderTitle {
            get {
                return ResourceManager.GetString("labelHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択されていません.
        /// </summary>
        public static string lblPatchFile {
            get {
                return ResourceManager.GetString("lblPatchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 書類受取ファイル.
        /// </summary>
        public static string rad1 {
            get {
                return ResourceManager.GetString("rad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 車検証QRコードCSV.
        /// </summary>
        public static string rad2 {
            get {
                return ResourceManager.GetString("rad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル番号CSV.
        /// </summary>
        public static string rad3 {
            get {
                return ResourceManager.GetString("rad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自社名・抹消対象ファイル.
        /// </summary>
        public static string rad4 {
            get {
                return ResourceManager.GetString("rad4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 書類返送対象ファイル.
        /// </summary>
        public static string rad5 {
            get {
                return ResourceManager.GetString("rad5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル名.
        /// </summary>
        public static string titleFileName {
            get {
                return ResourceManager.GetString("titleFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォーマット.
        /// </summary>
        public static string titleFormat {
            get {
                return ResourceManager.GetString("titleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル取込み.
        /// </summary>
        public static string titleImportFile {
            get {
                return ResourceManager.GetString("titleImportFile", resourceCulture);
            }
        }
    }
}
