//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gulliver.DoCol.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LibFullHalf {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibFullHalf() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gulliver.DoCol.Constants.Resources.LibFullHalf", typeof(LibFullHalf).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ガ.
        /// </summary>
        public static string ｶﾞ {
            get {
                return ResourceManager.GetString("ｶﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ギ.
        /// </summary>
        public static string ｷﾞ {
            get {
                return ResourceManager.GetString("ｷﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to グ.
        /// </summary>
        public static string ｸﾞ {
            get {
                return ResourceManager.GetString("ｸﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲ.
        /// </summary>
        public static string ｹﾞ {
            get {
                return ResourceManager.GetString("ｹﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゴ.
        /// </summary>
        public static string ｺﾞ {
            get {
                return ResourceManager.GetString("ｺﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ザ.
        /// </summary>
        public static string ｻﾞ {
            get {
                return ResourceManager.GetString("ｻﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジ.
        /// </summary>
        public static string ｼﾞ {
            get {
                return ResourceManager.GetString("ｼﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ズ.
        /// </summary>
        public static string ｽﾞ {
            get {
                return ResourceManager.GetString("ｽﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゼ.
        /// </summary>
        public static string ｾﾞ {
            get {
                return ResourceManager.GetString("ｾﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゾ.
        /// </summary>
        public static string ｿﾞ {
            get {
                return ResourceManager.GetString("ｿﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダ.
        /// </summary>
        public static string ﾀﾞ {
            get {
                return ResourceManager.GetString("ﾀﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヂ.
        /// </summary>
        public static string ﾁﾞ {
            get {
                return ResourceManager.GetString("ﾁﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヅ.
        /// </summary>
        public static string ﾂﾞ {
            get {
                return ResourceManager.GetString("ﾂﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デ.
        /// </summary>
        public static string ﾃﾞ {
            get {
                return ResourceManager.GetString("ﾃﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ド.
        /// </summary>
        public static string ﾄﾞ {
            get {
                return ResourceManager.GetString("ﾄﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バ.
        /// </summary>
        public static string ﾊﾞ {
            get {
                return ResourceManager.GetString("ﾊﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パ.
        /// </summary>
        public static string ﾊﾟ {
            get {
                return ResourceManager.GetString("ﾊﾟ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ビ.
        /// </summary>
        public static string ﾋﾞ {
            get {
                return ResourceManager.GetString("ﾋﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ピ.
        /// </summary>
        public static string ﾋﾟ {
            get {
                return ResourceManager.GetString("ﾋﾟ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブ.
        /// </summary>
        public static string ﾌﾞ {
            get {
                return ResourceManager.GetString("ﾌﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プ.
        /// </summary>
        public static string ﾌﾟ {
            get {
                return ResourceManager.GetString("ﾌﾟ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ベ.
        /// </summary>
        public static string ﾍﾞ {
            get {
                return ResourceManager.GetString("ﾍﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ペ.
        /// </summary>
        public static string ﾍﾟ {
            get {
                return ResourceManager.GetString("ﾍﾟ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ボ.
        /// </summary>
        public static string ﾎﾞ {
            get {
                return ResourceManager.GetString("ﾎﾞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポ.
        /// </summary>
        public static string ﾎﾟ {
            get {
                return ResourceManager.GetString("ﾎﾟ", resourceCulture);
            }
        }
    }
}
