//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gulliver.DoCol.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RsMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RsMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gulliver.DoCol.MessageUtility.RsMessage", typeof(RsMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        internal static string E0001 {
            get {
                return ResourceManager.GetString("E0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the permission to access this page/function..
        /// </summary>
        internal static string E0002 {
            get {
                return ResourceManager.GetString("E0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} existed. Please select another value..
        /// </summary>
        internal static string E0003 {
            get {
                return ResourceManager.GetString("E0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is duplicated. Please select another value..
        /// </summary>
        internal static string E0004 {
            get {
                return ResourceManager.GetString("E0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password is incorrect..
        /// </summary>
        internal static string E0005 {
            get {
                return ResourceManager.GetString("E0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password is empty..
        /// </summary>
        internal static string E0006 {
            get {
                return ResourceManager.GetString("E0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid..
        /// </summary>
        internal static string E0007 {
            get {
                return ResourceManager.GetString("E0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t send email, Please check again !.
        /// </summary>
        internal static string E0008 {
            get {
                return ResourceManager.GetString("E0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an integer value..
        /// </summary>
        internal static string E0009 {
            get {
                return ResourceManager.GetString("E0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input value into {0}..
        /// </summary>
        internal static string E0010 {
            get {
                return ResourceManager.GetString("E0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is(are) {1} successfully..
        /// </summary>
        internal static string I0001 {
            get {
                return ResourceManager.GetString("I0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been sent successfully..
        /// </summary>
        internal static string I0002 {
            get {
                return ResourceManager.GetString("I0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, please wait....
        /// </summary>
        internal static string I0003 {
            get {
                return ResourceManager.GetString("I0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error. Please input data for all required fields..
        /// </summary>
        internal static string I0004 {
            get {
                return ResourceManager.GetString("I0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully..
        /// </summary>
        internal static string I0005 {
            get {
                return ResourceManager.GetString("I0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have no log data !.
        /// </summary>
        internal static string I0006 {
            get {
                return ResourceManager.GetString("I0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to {0}?.
        /// </summary>
        internal static string I0007 {
            get {
                return ResourceManager.GetString("I0007", resourceCulture);
            }
        }
    }
}
