//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gulliver.DoCol.Constants.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScreenList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScreenList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gulliver.DoCol.Constants.Resources.ScreenList", typeof(ScreenList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string S1010 {
            get {
                return ResourceManager.GetString("S1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string S1011 {
            get {
                return ResourceManager.GetString("S1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string S1020 {
            get {
                return ResourceManager.GetString("S1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string S1021 {
            get {
                return ResourceManager.GetString("S1021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string S1030 {
            get {
                return ResourceManager.GetString("S1030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string S1031 {
            get {
                return ResourceManager.GetString("S1031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string S1040 {
            get {
                return ResourceManager.GetString("S1040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation;SearchOrListPage.
        /// </summary>
        public static string S2010 {
            get {
                return ResourceManager.GetString("S2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation.
        /// </summary>
        public static string S3010 {
            get {
                return ResourceManager.GetString("S3010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation.
        /// </summary>
        public static string S3020 {
            get {
                return ResourceManager.GetString("S3020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation.
        /// </summary>
        public static string S3030 {
            get {
                return ResourceManager.GetString("S3030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation.
        /// </summary>
        public static string S3110 {
            get {
                return ResourceManager.GetString("S3110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation.
        /// </summary>
        public static string S4010 {
            get {
                return ResourceManager.GetString("S4010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation.
        /// </summary>
        public static string S4020 {
            get {
                return ResourceManager.GetString("S4020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation.
        /// </summary>
        public static string S4030 {
            get {
                return ResourceManager.GetString("S4030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation.
        /// </summary>
        public static string S4031 {
            get {
                return ResourceManager.GetString("S4031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation.
        /// </summary>
        public static string S4040 {
            get {
                return ResourceManager.GetString("S4040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation.
        /// </summary>
        public static string S4110 {
            get {
                return ResourceManager.GetString("S4110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation;GLV.
        /// </summary>
        public static string S4120 {
            get {
                return ResourceManager.GetString("S4120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation;GLV.
        /// </summary>
        public static string S4120SEARCHMASTER {
            get {
                return ResourceManager.GetString("S4120SEARCHMASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation;GLV.
        /// </summary>
        public static string S4120SEARCHNAME {
            get {
                return ResourceManager.GetString("S4120SEARCHNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation;GLV.
        /// </summary>
        public static string S4120SELECTSETDETAIL {
            get {
                return ResourceManager.GetString("S4120SELECTSETDETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation.
        /// </summary>
        public static string S4130 {
            get {
                return ResourceManager.GetString("S4130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation.
        /// </summary>
        public static string S4140 {
            get {
                return ResourceManager.GetString("S4140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation.
        /// </summary>
        public static string S4150 {
            get {
                return ResourceManager.GetString("S4150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string S5010 {
            get {
                return ResourceManager.GetString("S5010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string S5030 {
            get {
                return ResourceManager.GetString("S5030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string S5040 {
            get {
                return ResourceManager.GetString("S5040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        public static string S6010 {
            get {
                return ResourceManager.GetString("S6010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        public static string S6030 {
            get {
                return ResourceManager.GetString("S6030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        public static string S6040 {
            get {
                return ResourceManager.GetString("S6040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing;SearchOrListPage.
        /// </summary>
        public static string S7010 {
            get {
                return ResourceManager.GetString("S7010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        public static string S7010LIST {
            get {
                return ResourceManager.GetString("S7010LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        public static string S7020 {
            get {
                return ResourceManager.GetString("S7020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string S9010 {
            get {
                return ResourceManager.GetString("S9010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string S9020 {
            get {
                return ResourceManager.GetString("S9020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string S9030 {
            get {
                return ResourceManager.GetString("S9030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string S9031 {
            get {
                return ResourceManager.GetString("S9031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string S9040 {
            get {
                return ResourceManager.GetString("S9040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string S9041 {
            get {
                return ResourceManager.GetString("S9041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string S9050 {
            get {
                return ResourceManager.GetString("S9050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string S9051 {
            get {
                return ResourceManager.GetString("S9051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLV.
        /// </summary>
        public static string S9100 {
            get {
                return ResourceManager.GetString("S9100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLV.
        /// </summary>
        public static string S9110 {
            get {
                return ResourceManager.GetString("S9110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLV.
        /// </summary>
        public static string S9120 {
            get {
                return ResourceManager.GetString("S9120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLV.
        /// </summary>
        public static string S9121 {
            get {
                return ResourceManager.GetString("S9121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLV.
        /// </summary>
        public static string S9130 {
            get {
                return ResourceManager.GetString("S9130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLV.
        /// </summary>
        public static string S9131 {
            get {
                return ResourceManager.GetString("S9131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLV.
        /// </summary>
        public static string S9140 {
            get {
                return ResourceManager.GetString("S9140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLV.
        /// </summary>
        public static string S9141 {
            get {
                return ResourceManager.GetString("S9141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLV.
        /// </summary>
        public static string S9150 {
            get {
                return ResourceManager.GetString("S9150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLV.
        /// </summary>
        public static string S9160 {
            get {
                return ResourceManager.GetString("S9160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLV.
        /// </summary>
        public static string S9161 {
            get {
                return ResourceManager.GetString("S9161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLV.
        /// </summary>
        public static string S9170 {
            get {
                return ResourceManager.GetString("S9170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLV.
        /// </summary>
        public static string S9180 {
            get {
                return ResourceManager.GetString("S9180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLV.
        /// </summary>
        public static string S9181 {
            get {
                return ResourceManager.GetString("S9181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLV.
        /// </summary>
        public static string S9190 {
            get {
                return ResourceManager.GetString("S9190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLV.
        /// </summary>
        public static string S9191 {
            get {
                return ResourceManager.GetString("S9191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLV.
        /// </summary>
        public static string S91B0 {
            get {
                return ResourceManager.GetString("S91B0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLV.
        /// </summary>
        public static string S91B1 {
            get {
                return ResourceManager.GetString("S91B1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLV.
        /// </summary>
        public static string S9920 {
            get {
                return ResourceManager.GetString("S9920", resourceCulture);
            }
        }
    }
}
