//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gulliver.DoCol.ReportServices.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IServices")]
    public interface IServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/ExportPDF", ReplyAction="http://tempuri.org/IServices/ExportPDFResponse")]
        System.IO.MemoryStream ExportPDF(string reportID, System.Data.DataSet dataSource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/ExportPDF", ReplyAction="http://tempuri.org/IServices/ExportPDFResponse")]
        System.Threading.Tasks.Task<System.IO.MemoryStream> ExportPDFAsync(string reportID, System.Data.DataSet dataSource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/ExportPDFOutput", ReplyAction="http://tempuri.org/IServices/ExportPDFOutputResponse")]
        Gulliver.DoCol.ReportServices.Service.ExportPDFOutputResponse ExportPDFOutput(Gulliver.DoCol.ReportServices.Service.ExportPDFOutputRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/ExportPDFOutput", ReplyAction="http://tempuri.org/IServices/ExportPDFOutputResponse")]
        System.Threading.Tasks.Task<Gulliver.DoCol.ReportServices.Service.ExportPDFOutputResponse> ExportPDFOutputAsync(Gulliver.DoCol.ReportServices.Service.ExportPDFOutputRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/ExportCSVOutput", ReplyAction="http://tempuri.org/IServices/ExportCSVOutputResponse")]
        Gulliver.DoCol.ReportServices.Service.ExportCSVOutputResponse ExportCSVOutput(Gulliver.DoCol.ReportServices.Service.ExportCSVOutputRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/ExportCSVOutput", ReplyAction="http://tempuri.org/IServices/ExportCSVOutputResponse")]
        System.Threading.Tasks.Task<Gulliver.DoCol.ReportServices.Service.ExportCSVOutputResponse> ExportCSVOutputAsync(Gulliver.DoCol.ReportServices.Service.ExportCSVOutputRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportPDFOutput", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExportPDFOutputRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string reportID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataSet dataSource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string messErr;
        
        public ExportPDFOutputRequest() {
        }
        
        public ExportPDFOutputRequest(string reportID, System.Data.DataSet dataSource, string messErr) {
            this.reportID = reportID;
            this.dataSource = dataSource;
            this.messErr = messErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportPDFOutputResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExportPDFOutputResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.MemoryStream ExportPDFOutputResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string messErr;
        
        public ExportPDFOutputResponse() {
        }
        
        public ExportPDFOutputResponse(System.IO.MemoryStream ExportPDFOutputResult, string messErr) {
            this.ExportPDFOutputResult = ExportPDFOutputResult;
            this.messErr = messErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportCSVOutput", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExportCSVOutputRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string reportID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataSet dataSource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string messErr;
        
        public ExportCSVOutputRequest() {
        }
        
        public ExportCSVOutputRequest(string reportID, System.Data.DataSet dataSource, string messErr) {
            this.reportID = reportID;
            this.dataSource = dataSource;
            this.messErr = messErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportCSVOutputResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExportCSVOutputResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.MemoryStream ExportCSVOutputResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string messErr;
        
        public ExportCSVOutputResponse() {
        }
        
        public ExportCSVOutputResponse(System.IO.MemoryStream ExportCSVOutputResult, string messErr) {
            this.ExportCSVOutputResult = ExportCSVOutputResult;
            this.messErr = messErr;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicesChannel : Gulliver.DoCol.ReportServices.Service.IServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesClient : System.ServiceModel.ClientBase<Gulliver.DoCol.ReportServices.Service.IServices>, Gulliver.DoCol.ReportServices.Service.IServices {
        
        public ServicesClient() {
        }
        
        public ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.MemoryStream ExportPDF(string reportID, System.Data.DataSet dataSource) {
            return base.Channel.ExportPDF(reportID, dataSource);
        }
        
        public System.Threading.Tasks.Task<System.IO.MemoryStream> ExportPDFAsync(string reportID, System.Data.DataSet dataSource) {
            return base.Channel.ExportPDFAsync(reportID, dataSource);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gulliver.DoCol.ReportServices.Service.ExportPDFOutputResponse Gulliver.DoCol.ReportServices.Service.IServices.ExportPDFOutput(Gulliver.DoCol.ReportServices.Service.ExportPDFOutputRequest request) {
            return base.Channel.ExportPDFOutput(request);
        }
        
        public System.IO.MemoryStream ExportPDFOutput(string reportID, System.Data.DataSet dataSource, ref string messErr) {
            Gulliver.DoCol.ReportServices.Service.ExportPDFOutputRequest inValue = new Gulliver.DoCol.ReportServices.Service.ExportPDFOutputRequest();
            inValue.reportID = reportID;
            inValue.dataSource = dataSource;
            inValue.messErr = messErr;
            Gulliver.DoCol.ReportServices.Service.ExportPDFOutputResponse retVal = ((Gulliver.DoCol.ReportServices.Service.IServices)(this)).ExportPDFOutput(inValue);
            messErr = retVal.messErr;
            return retVal.ExportPDFOutputResult;
        }
        
        public System.Threading.Tasks.Task<Gulliver.DoCol.ReportServices.Service.ExportPDFOutputResponse> ExportPDFOutputAsync(Gulliver.DoCol.ReportServices.Service.ExportPDFOutputRequest request) {
            return base.Channel.ExportPDFOutputAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gulliver.DoCol.ReportServices.Service.ExportCSVOutputResponse Gulliver.DoCol.ReportServices.Service.IServices.ExportCSVOutput(Gulliver.DoCol.ReportServices.Service.ExportCSVOutputRequest request) {
            return base.Channel.ExportCSVOutput(request);
        }
        
        public System.IO.MemoryStream ExportCSVOutput(string reportID, System.Data.DataSet dataSource, ref string messErr) {
            Gulliver.DoCol.ReportServices.Service.ExportCSVOutputRequest inValue = new Gulliver.DoCol.ReportServices.Service.ExportCSVOutputRequest();
            inValue.reportID = reportID;
            inValue.dataSource = dataSource;
            inValue.messErr = messErr;
            Gulliver.DoCol.ReportServices.Service.ExportCSVOutputResponse retVal = ((Gulliver.DoCol.ReportServices.Service.IServices)(this)).ExportCSVOutput(inValue);
            messErr = retVal.messErr;
            return retVal.ExportCSVOutputResult;
        }
        
        public System.Threading.Tasks.Task<Gulliver.DoCol.ReportServices.Service.ExportCSVOutputResponse> ExportCSVOutputAsync(Gulliver.DoCol.ReportServices.Service.ExportCSVOutputRequest request) {
            return base.Channel.ExportCSVOutputAsync(request);
        }
    }
}
